version: '3.8'

services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - dsys-network

  backend:
    build: ./server
    ports:
      - "8080:8080"
    networks:
      - dsys-network

networks:
  dsys-network:
