version: '3'

services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    networks:
      - dsys-network
    depends_on:
      - backend
      - reverse-proxy

  backend:
    build: ./server
    networks:
      - dsys-network
    labels:
      - "traefik.http.routers.backend.rule=Host(`backend-dsy-challengetask2`)"
    depends_on:
      - reverse-proxy
      - mongo
    deploy:
      replicas: 2

  reverse-proxy:
    image: traefik:v2.10
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - dsys-network
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - todo-db:/data/db

volumes:
  todo-db:
networks:
  dsys-network:
