version: '3'

services:
  frontend:
    build: ./client
    networks:
      - dsys-network
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - loadbalancer

  backend:
    build: ./server
    networks:
      - dsys-network
    depends_on:
      - loadbalancer
    deploy:
      replicas: 2

  loadbalancer:
    image: traefik:latest
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml
      - ./certs/key.pem:/etc/traefik/key.pem
      - ./certs/cert.pem:/etc/traefik/cert.pem
      - ./certs/cert.pem:/etc/ssl/certs/cert.pem
    networks:
      - dsys-network
    restart: unless-stopped

networks:
  dsys-network:
