# Dynamic configuration for backend and frontend instances
# Use this file to define additional frontend and backend instances dynamically

# Backend configuration
[http.routers]
[http.routers.backend]
rule = "Host(`backend.example.com`)"
service = "backend"
[http.services]
[http.services.backend]
[http.services.backend.loadBalancer]
[[http.services.backend.loadBalancer.servers]]
url = "http://backend:3000"

# Frontend configuration
[http.routers]
[http.routers.frontend]
rule = "Host(`frontend.example.com`)"
service = "frontend"
[http.services]
[http.services.frontend]
[http.services.frontend.loadBalancer]
[[http.services.frontend.loadBalancer.servers]]
url = "http://frontend:80"
