tls:
  certificates:
    - certFile: "/etc/traefik/cert.pem"
      keyFile: "/etc/traefik/key.pem"
  stores:
    default:
      defaultCertificate:
        certFile: "/etc/traefik/cert.pem"
        keyFile: "/etc/traefik/key.pem"
